services:
  - type: web
    name: bookproject
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn bookproject.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://bookvault_gb8r_user:uADFUkkVOf0DHON1YXbtENCVKGOO1Ta0@dpg-d1oan7nfte5s73b2of30-a.oregon-postgres.render.com/bookvault_gb8r
      - key: SECRET_KEY
        value: w$!1z@3^k#8!2b!9n@4^p!7z@1x!2c!3v@5^l!6m@8^q!0r!2s!4t!6u!8w!0y!2z
      - key: DEBUG
        value: False
