# Generated by Django 5.2.4 on 2025-07-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy'), ('science', 'Science'), ('biography', 'Biography'), ('romance', 'Romance'), ('history', 'History'), ('selfhelp', 'Self-Help'), ('children', 'Children'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in INR', max_digits=8),
        ),
    ]
