# Generated by Django 5.2.4 on 2025-07-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_cart_cartitem_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discount_percent',
            field=models.PositiveIntegerField(default=10, help_text='Discount percent (10-25%)'),
        ),
    ]
