# Generated by Django 5.2.4 on 2025-07-08 19:34

from django.db import migrations, models
import django.utils.timezone

def set_cartitem_created_at(apps, schema_editor):
    CartItem = apps.get_model('bookapp', 'CartItem')
    now = django.utils.timezone.now()
    for item in CartItem.objects.all():
        item.created_at = now
        item.save()

class Migration(migrations.Migration):
    dependencies = [
        ('bookapp', '0005_readbook'),
    ]
    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(set_cartitem_created_at),
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=False),
        ),
    ]
